version: '3.8'

services:
  php:
    image: "hexomyns/symfo-groupe3:latest"
    container_name: php_container
    restart: unless-stopped
    ports:
      - "${PHP_PORT}:80"
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      MESSENGER_TRANSPORT_DSN: ${MESSENGER_TRANSPORT_DSN}
      MAILER_DSN: ${MAILER_DSN}
      SOCIETY: ${SOCIETY}
      DB_HOST: db
      DB_TYPE: ${DB_TYPE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_PORT: ${DB_PORT}
    depends_on:
      - db
    # volumes:
    #   - ./php_volume:/var/www/html

  db:
    image: mysql:${DB_VERSION}
    container_name: mysql_container
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: