version: '3.8'

services:
  web:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - php_volume:/var/www/html:cached
      - symfony_app_var:/var/www/html/var
      - symfony_app_vendor:/var/www/html/vendor
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    environment:
      - NGINX_BACKEND_DOMAIN=${NGINX_BACKEND_DOMAIN}
    networks:
      - symfony_app
    links:
      - php
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - php_volume:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - web
    command: certonly --webroot --webroot-path=/var/www/html --email mickaeldev@hexolis.com --agree-tos --no-eff-email --staging -d ${NGINX_BACKEND_DOMAIN}

  php:
    image: hexomyns/symfo-groupe3:latest
    container_name: php_container
    restart: unless-stopped
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      MESSENGER_TRANSPORT_DSN: ${MESSENGER_TRANSPORT_DSN}
      MAILER_DSN: ${MAILER_DSN}
      SOCIETY: ${SOCIETY}
      DB_HOST: db
      DB_TYPE: ${DB_TYPE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_PORT: ${DB_PORT}
    volumes:
      - php_volume:/var/www/html:cached
      - symfony_app_var:/var/www/html/var
      - symfony_app_vendor:/var/www/html/vendor
    networks:
      - symfony_app
    depends_on:
      - db

  db:
    image: mysql:${DB_VERSION}
    container_name: mysql_container
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    networks:
      - symfony_app
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  php_volume:
  symfony_app_var:
  symfony_app_vendor:
  dbdata:
  certbot-etc:
  certbot-var:

networks:
  symfony_app: